site_name: Symphony eHRM User Manual
theme:
  name: material
  palette:
    scheme: slate  # Dark mode default (ElevenLabs)
  font:
    text: Roboto  # Clean font like ElevenLabs
  icon:
    logo: material/library  # Optional: Default icon
  features:
    - palette.toggle  # Light/dark toggle (like ElevenLabs)
    - palette.autocomplete
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - Initial Setup:
    - Leave Type Setup: initial-setup/leave-type-setup.md
  - Employee Setup:
    - Adding a New Employee: employee-setup/adding-employee.md
  - Leave Management:
    - Leave Allocation & Application: leave-management/leave-allocation-application.md
  - Payroll Management:
    - Running Payroll: payroll-management/running-payroll.md
plugins:
  - search  # Adds search bar (ElevenLabs-like)
docs_dir: docs
